### ISSUE TITLE
fail to brew install hadolint in docker file

### ISSUE THREAD

**Issue by Adeljoo** [peaceiris/hugo-extended-docker#2]
I try to use the action yml and I could not run and complain about hadolint.

**Comment by peaceiris** [comment]
Tell me more details.

**Comment by Adeljoo** [comment]
I copied and pasted the image and push yml files in my workflow. added docker file and .hadolint.yaml to my repo. But the staus of action is failed.

**Comment by peaceiris** [comment]
Are you working on [Adeljoo/testMd](https://github.com/Adeljoo/testMd)? The Docker file does not work as GitHub Action. GitHub Actions runner does not support `docker build --build-arg`.

This issue is not related to this repo, so I close this.

Ask about GitHub Actions on the forum [GitHub Actions - GitHub Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions).

**Comment by Adeljoo** [comment]
Thanks, I found the problem. Can I ask about the DOCKER_HUB_BASE_NAME is set to your name right now, should I change it to my account username? how about the following line
`echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u (**your username**) --password-stdin`
